ToDo_WebClient/Models/AppConstants.cs
namespace ToDo_WebClient.Models
{
    public class AppConstants
    {
        public static string BaseUrl = "https://localhost:7221/";
        public static string TodoAPI = "todoitems";
    }
}

ToDo_WebClient/Models/TodoDTO.cs
using System.ComponentModel.DataAnnotations;

namespace ToDo_WebClient.Models
{
    public class TodoDTO
    {
        public int ID { get; set; }
        [Required]
        public string? Name { get; set; }
        public DateTime CreatedTime { get; set; } = DateTime.Now;
        [Required]
        public string? Description { get; set; }
        public bool Completed { get; set; }
        [Required]
        public Priority Priority { get; set; }
    }

    public enum Priority
    {
        Low,
        Normal,
        High
    }
}

ToDo_WebClient/Pages/Account/Login.cshtml.cs
using Auth0.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ToDo_WebClient.Pages.Account
{
    public class LoginModel : PageModel
    {
        public async Task OnGet(string returnUrl = "/")
        {
            var authenticationProperties = new LoginAuthenticationPropertiesBuilder()
                .WithRedirectUri(returnUrl)
                .Build();

            await HttpContext.ChallengeAsync(Auth0Constants.AuthenticationScheme, authenticationProperties);
        }
    }
}

ToDo_WebClient/Pages/Account/Logout.cshtml.cs
using Auth0.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ToDo_WebClient.Pages.Account
{
    [Authorize]
    public class LogoutModel : PageModel
    {
        public async Task OnGet()
        {
            var authenticationProperties = new LogoutAuthenticationPropertiesBuilder()
                .WithRedirectUri(Url.Page("Index"))
                .Build();

            await HttpContext.SignOutAsync(Auth0Constants.AuthenticationScheme, authenticationProperties);
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
        }
    }
}

ToDo_WebClient/Pages/Account/Profile.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Security.Claims;

namespace ToDo_WebClient.Pages.Account
{
    [Authorize]
    public class ProfileModel : PageModel
    {
        [BindProperty(SupportsGet = true)]
        public string? Name { get; set; }

        [BindProperty(SupportsGet = true)]
        public string? Email { get; set; }

        [BindProperty(SupportsGet = true)]
        public string? ProfileImage { get; set; }

        public void OnGet()
        {
            Name = User.Identity.Name;
            Email = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.Email)?.Value;
            ProfileImage = User.Claims.FirstOrDefault(c => c.Type == "picture")?.Value;
        }
    }
}

ToDo_WebClient/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace ToDo_WebClient.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

ToDo_WebClient/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Security.Claims;
using ToDo_WebClient.Models;
using ToDo_WebClient.Services;

namespace ToDo_WebClient.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        private readonly ITodoService _todoService;

        [BindProperty(SupportsGet = true)]
        public TodoDTO TodoItem { get; set; }
        [BindProperty(SupportsGet = true)]
        public string? UserClaims { get; set; }

        public IndexModel(ILogger<IndexModel> logger, ITodoService todoService)
        {
            _logger = logger;
            _todoService = todoService;
        }

        public void OnGet()
        {
            
        }

        public async Task<IActionResult> OnPost()
        {
            if (ModelState.IsValid)
            {
                await _todoService.CreateAsync(TodoItem);
                return RedirectToPage("/Index");
            }
            else
            {
                return Page();
            }
            return RedirectToPage("/Index");
        }
    }
}

ToDo_WebClient/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ToDo_WebClient.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

ToDo_WebClient/Pages/Todo/CreateTodo.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ToDo_WebClient.Pages.Todo
{
    public class CreateTodoModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

ToDo_WebClient/Pages/Todo/EditTodo.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.VisualBasic;
using ToDo_WebClient.Models;
using ToDo_WebClient.Services;

namespace ToDo_WebClient.Pages.Todo
{
    public class EditTodoModel : PageModel
    {
        private readonly ITodoService _todoService;

        public EditTodoModel(ITodoService todoService)
        {
            _todoService = todoService;
        }
        [BindProperty(SupportsGet = true)]
        public TodoDTO Todoitem { get; set; }

        public async Task<IActionResult> OnGet(int TodoId)
        {
            Todoitem = await _todoService.GetItemByIdAsync(TodoId);
            return Page();
        }

        public async Task<IActionResult> OnPost(bool editTodo, bool deleteTodo)
        {
            if (ModelState.IsValid)
            {
                if (editTodo)
                {
                    if (Todoitem != null)
                    {                        
                        await _todoService.Update(Todoitem.ID, Todoitem);
                        return RedirectToPage("/Todo/ToDoItems");
                    }
                }
                else if (deleteTodo)
                {
                    await _todoService.Delete(Todoitem.ID);
                    return RedirectToPage("/Todo/ToDoItems");
                }
                return RedirectToPage("/Todo/ToDoItems");
            }
            else
            {
                return Page();
            }
        }
    }
}

ToDo_WebClient/Pages/Todo/ToDoItems.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using ToDo_WebClient.Services;
using ToDo_WebClient.Models;
using Microsoft.AspNetCore.Mvc;

namespace ToDo_WebClient.Pages.Todo
{
    public class ToDoItemsModel : PageModel
    {
        private readonly ITodoService _toDoService;

        public ToDoItemsModel(ITodoService todoService)
        {
            _toDoService = todoService;
        }

        [BindProperty]
        public List<TodoDTO> TodoItems { get; set; }
        [BindProperty]
        public TodoDTO TodoItem { get; set; }

        public async Task<IActionResult> OnGet()
        {
            TodoItems = await _toDoService.GetItemsAsync();
            return Page();
        }

        public async Task<IActionResult> OnPostCreateTodo()
        {
            if (ModelState.IsValid)
            {
                await _toDoService.CreateAsync(TodoItem);
                return RedirectToPage("/Todo/ToDoItems");
            }
            else
            {
                return RedirectToPage("/Error");
            }
            return RedirectToPage("/Todo/ToDoItems");
        }

        public async Task<IActionResult> OnPostCompleteTodo(int iD)
        {
            TodoItem = await _toDoService.GetItemByIdAsync(iD);
            TodoItem.Completed = true;
            await _toDoService.Update(TodoItem.ID, TodoItem);
            return RedirectToPage("/Todo/ToDoItems");
        }
    }
}

ToDo_WebClient/Pages/Account/Login.cshtml
@page
@model ToDo_WebClient.Pages.Account.LoginModel
@{
}

ToDo_WebClient/Pages/Account/Logout.cshtml
@page
@model ToDo_WebClient.Pages.Account.LogoutModel
@{
}

ToDo_WebClient/Pages/Account/Profile.cshtml
@page
@model ToDo_WebClient.Pages.Account.ProfileModel
@{
}

<div class="container text-center">
    <div class="row">
        <div class="col-3"></div>
        <div class="col-6">
            <img src="@Model.ProfileImage" />
        </div>   
        <div class="col-3"></div>
    </div>
    <div class="row mt-2">
        <h3>@Model.Name</h3>
    </div>
    <div class="row mt-2">
        <h3>@Model.Email</h3>
    </div>
</div>

ToDo_WebClient/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1>Web API, Web Client and furthermore Auth0.</h1>
    <p>This is a project made to practice the above mentioned. </p>
    <p>It's made for a school project, so that I can become more familiar with the concepts of everything.</p>
    <p>Start by creating a new To-do item: <button type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#staticBackdrop">Create ToDo</button>
</div>

<form method="post">
    <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="staticBackdropLabel">Create a new To-do</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="row mb-2">
                        <div class="col-4">
                            <label>Name:</label>
                        </div>
                        <div class="col-8">
                            <input type="text" asp-for="@Model.TodoItem.Name" placeholder="Enter name..." id="Name"/>
                            <br />
                            <span class="text-danger" asp-validation-for="@Model.TodoItem.Name"></span>
                        </div>
                    </div>
                    <div class="row mb-2">
                        <div class="col-4">
                            <label>Description:</label>
                        </div>
                        <div class="col-8">
                            <input type="text" asp-for="@Model.TodoItem.Description" placeholder="Enter description..." />
                            <br />
                            <span class="text-danger" asp-validation-for="@Model.TodoItem.Description"></span>
                        </div>
                    </div>
                    <div class="row mb-2">
                        <div class="col-4">
                            <label>Priority:</label>
                        </div>
                        <div class="col-8">
                            <select asp-for="@Model.TodoItem.Priority" id="Priority" 
                                    class="form-control">
                                <option value="0">High</option>
                                <option value="1">Normal</option>
                                <option value="2">Low</option>
                            </select>
                            <br />
                            <span class="text-danger" asp-validation-for="@Model.TodoItem.Priority"></span>
                        </div>
                    </div>
                    <div class="row mb-2">
                        <div class="col-4">
                            <label>Completed:</label>
                        </div>
                        <div class="col-8">
                            <input type="checkbox" asp-for="@Model.TodoItem.Completed">
                        </div>
                    </div>      
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-success">Create</button>
                </div>
            </div>
        </div>
    </div>
</form>

ToDo_WebClient/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ToDo_WebClient</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ToDo_WebClient.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">ToDo_WebClient</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Todo/ToDoItems">To do items</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav flex-grow-1 me-auto">
                        @if (User.Identity.IsAuthenticated == true)
                        {
                            <li class="nav-item text-right">
                                <a class="nav-link text-dark" asp-page="/Account/Profile">Welcome @User.Identity.Name !</a>
                            </li>
                        }

                        <li class="nav-item text-rigt">
                            @if (User.Identity.IsAuthenticated == true)
                            {
                                <a class="nav-link text-dark" asp-area="" asp-page="/Account/Logout">Logout</a>
                            }
                            else
                            {
                                <a class="nav-link text-dark text-right" asp-area="" asp-page="/Account/Login">Login</a>
                            }
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ToDo_WebClient - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ToDo_WebClient/Pages/Todo/CreateTodo.cshtml
@page
@model ToDo_WebClient.Pages.Todo.CreateTodoModel
@{
    ViewData["Title"] = "Create a new To do item";
}

ToDo_WebClient/Pages/Todo/EditTodo.cshtml
@page "{TodoId:int}"
@model ToDo_WebClient.Pages.Todo.EditTodoModel
@{
}

<div class="container">
    <h3 class="text-center">You are about to edit: <b>@Model.Todoitem.Name</b></h3>
    <div class="row">
        <div class="col-md-3"></div>
        <form method="post" class="card border col-md-6 form-bg-color">
            <input type="hidden" asp-for="@Model.Todoitem.ID" />
            <div class="row">
                <div>
                    <div class="input-group mt-4">
                        <div class="input-group-prepend col-md-3">
                            <span class="input-group-text">Name: </span>
                        </div>
                        <input type="text" asp-for="@Model.Todoitem.Name" class="form-control col-md-9" placeholder="@Model.Todoitem.Name" />
                        <br />
                        <span class="text-danger" asp-validation-for="@Model.Todoitem.Name"></span>
                    </div>
                </div>
                <div>
                    <div class="input-group mt-4">
                        <div class="input-group-prepend col-md-3">
                            <span class="input-group-text">Description: </span>
                        </div>
                        <input type="text" asp-for="@Model.Todoitem.Description" class="form-control col-md-9" placeholder="@Model.Todoitem.Description" />
                        <br />
                        <span class="text-danger" asp-validation-for="@Model.Todoitem.Description"></span>
                    </div>
                </div>
            </div>
            <div class="row mt-3">
                <div>
                    <div class="mb-3">
                        <div class="input-group">
                            <div class="input-group-prepend col-md-3">
                                <span class="input-group-text">Choose priority: </span>
                            </div>
                            <select asp-for="@Model.Todoitem.Priority" id="Priority" class="form-control">
                                <option value="0">High</option>
                                <option value="1">Normal</option>
                                <option value="2">Low</option>
                            </select>
                            <br />
                            <span class="text-danger" asp-validation-for="@Model.Todoitem.Priority"></span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="mb-3 col-md-6">
                    <div class="input-group">
                        <div class="input-group-prepend col-md-9">
                            <span class="input-group-text">Completed: </span>
                        </div>
                        <div class="form-control col-md-3">
                            <input type="checkbox" asp-for="@Model.Todoitem.Completed" class="form-check-input ms-3" />
                        </div>
                    </div>
                </div>
                <div class="mb-3 col-md-6">
                    <div class="input-group">
                        <div class="input-group-prepend col-md-4">
                            <span class="input-group-text">Created: </span>
                        </div>
                        <input type="text" asp-for="@Model.Todoitem.CreatedTime" readonly class="form-control col-md-8" placeholder="@Model.Todoitem.CreatedTime" />
                    </div>
                </div>
            </div>
            <div class="row mt-3">
                <hr />
            </div>
            <div class="row mb-3">
                <div class="d-flex flex-row justify-content-center">
                    <div class="me-4">
                        <a class="btn btn-warning" asp-page="/Todo/ToDoItems">Return</a>
                    </div>
                    <div class="ms-4">
                        <button type="submit" name="editTodo" class="btn btn-success" value="true">Edit</button>
                    </div>
                    <div class="ms-4">
                        <button type="submit" class="btn btn-danger" value="true" name="deleteTodo" onclick="return confirm('Are you sure you want to delete this To-do item?')">Delete</button>
                    </div>                    
                </div>
            </div>
        </form>
    </div>
</div>

ToDo_WebClient/Pages/Todo/ToDoItems.cshtml
@page
@model ToDo_WebClient.Pages.Todo.ToDoItemsModel
@{
    ViewData["Title"] = "List of To do items";
}

<div class="container">
    <div class="row">
        <div class="col-10">
            <h1>To do items</h1>
        </div>
        <div class="col-2">
            <button type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#staticBackdrop">Create ToDo</button>
        </div>
    </div>
    <div class="row">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Completed</th>
                    <th>Name</th>
                    <th>Priority</th>
                    <th>Creation Time</th>
                    <th>Description</th>
                </tr>
            </thead>
            <tbody>
                @if (Model.TodoItems is not null)
                {
                    @foreach (var item in Model.TodoItems)
                    {
                        <input />
                        <tr>
                            <td>
                                <form method="post" asp-page-handler="CompleteTodo" asp-route-id="@item.ID">
                                    <button type="submit" class="btn btn-success" name="isCompleted" asp-for="@item.Completed">Mark as complete</button>
                                </form>
                            </td>
                            <td>@item.Name</td>
                            <td>@item.Priority</td>
                            <td>@item.CreatedTime</td>
                            <td>
                                <a asp-page="/Todo/EditTodo" asp-route-TodoId="@item.ID">@item.Description</a>
                            </td>
                        </tr>
                    }
                }
            </tbody>
        </table>
    </div>
</div>

<!-- MODAL -->
<form method="post" asp-page-handler="CreateTodo">
    <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="staticBackdropLabel">Create a new To-do</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="row mb-2">
                        <div class="col-4">
                            <label>Name:</label>
                        </div>
                        <div class="col-8">
                            <input type="text" asp-for="@Model.TodoItem.Name" placeholder="Enter name..." id="Name" />
                            <br />
                            <span class="text-danger" asp-validation-for="@Model.TodoItem.Name"></span>
                        </div>
                    </div>
                    <div class="row mb-2">
                        <div class="col-4">
                            <label>Description:</label>
                        </div>
                        <div class="col-8">
                            <input type="text" asp-for="@Model.TodoItem.Description" placeholder="Enter description..." />
                            <br />
                            <span class="text-danger" asp-validation-for="@Model.TodoItem.Description"></span>
                        </div>
                    </div>
                    <div class="row mb-2">
                        <div class="col-4">
                            <label>Priority:</label>
                        </div>
                        <div class="col-8">
                            <select asp-for="@Model.TodoItem.Priority" id="Priority"
                                    class="form-control">
                                <option value="0">High</option>
                                <option value="1">Normal</option>
                                <option value="2">Low</option>
                            </select>
                            <br />
                            <span class="text-danger" asp-validation-for="@Model.TodoItem.Priority"></span>
                        </div>
                    </div>
                    <div class="row mb-2">
                        <div class="col-4">
                            <label>Completed:</label>
                        </div>
                        <div class="col-8">
                            <input type="checkbox" asp-for="@Model.TodoItem.Completed">
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-success">Create</button>
                </div>
            </div>
        </div>
    </div>
</form>